### ISSUE TITLE
--format is ignored?

### ISSUE THREAD

**Issue by arademaker** [delph-in/delphin.edm#4]
```
(venv-dev) ar@leme wn % delphin edm -vv --format=dmrx  ~/hpsg/terg/tsdb/gold/omw omw-parsed
... 
Traceback (most recent call last):
  File "/Users/ar/venv-dev/bin/delphin", line 11, in <module>
    load_entry_point('PyDelphin==1.4.1', 'console_scripts', 'delphin')()
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/main.py", line 42, in main
    args.func(args)
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/cli/edm.py", line 35, in call_compute
    p, r, f = edm.compute(
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/edm.py", line 235, in compute
    totals: Match = accumulate(
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/edm.py", line 154, in accumulate
    for i, (gold, test) in enumerate(zip_longest(golds, tests), 1):
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/cli/edm.py", line 59, in _iter_representations
    yield from_mrs(result.mrs(), predicate_modifiers=True)
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/eds/_operations.py", line 45, in from_mrs
    deps = _mrs_args_to_basic_deps(m, hcmap, reps)
  File "/Users/ar/venv-dev/lib/python3.8/site-packages/delphin/eds/_operations.py", line 95, in _mrs_args_to_basic_deps
    tgt = reps[lbl][0].id
KeyError: 'h23'
```

The same happens with `-f dmrs`. So whatever `-f` is passed, the code still calls the `eds` operations. Does it make sense?

**Comment by goodmami** [comment]
The `--format` option is for decoding the files on disk, so if you are giving it a profile, I'm pretty sure it assumes the profile contains MRSs and it tries to convert to EDS. If you first convert the MRSs to DMRS you can use `--format=dmrx` (or another DMRS codec, as appropriate for your conversion).

I, however, see that you want to configure the dependency relation that MRSs are converted to, which seems like a reasonable feature request, but the workaround that you first convert to DMRS then use EDM isn't so hard, either.

**Comment by goodmami** [comment]
I'm closing this, as it stems from a misunderstanding and I doubt I'll add the ability to configure the target conversion format before EDM computation.
